# Permalinks
#
permalink:           /:categories/:year/:month/:day/:title/

# Setup
title:               Thee Blog
tagline:             New site
description:         The test site
url:                 http://yoururl.com
baseurl:             https://toedtwiley.github.io/
paginate:            5

# Plugins, Tags, Categories and Analytics  
plugins:          [jekyll-paginate]

# About/contact
author:
  name:              Andrew Toedt-Wiley
  url:               https://www.linkedin.com/in/andrew-toedt-wiley/
  email:             toedtwiley@gmail.com
